[package]
name = "rust_google_oauth2"
version = "0.2.0"
authors = ["Siamion Makarski <s.makarski.s@gmail.com>"]
edition = "2018"

[dependencies]
url = "1.7.2"
serde = "1"
serde_json = "1.0.38"
serde_derive = "1"
dirs = "1.0"
reqwest = "0.9.11"
mockito = "0.17.0"
